#!/bin/bash

# Save the old HOME so we can revert after running the script.
# Set $HOME to the REPO_DIR temporarily.
OLD_HOME=$HOME

##########
cd $OPENSHIFT_REPO_DIR
export HOME=$OPENSHIFT_REPO_DIR

##########
echo "INFO: Running 'grunt build'"
grunt build

#########
export HOME=$OLD_HOME
echo "INFO: HOME is $HOME"
