// See here for the list from Google: https://www.gstatic.com/charts/regioncoder/0/geocodes/countries_en.js
// See here for countries matched to region & continent https://statisticstimes.com/geography/countries-by-continents.php

module.exports = [
  {
    country: 'Afghanistan',
    region: 'Southern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Aland Islands',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Albania',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Algeria',
    region: 'Northern Africa',
    subRegion: '',
    continent: 'Africa',
  },
  {
    country: 'American Samoa',
    region: 'Polynesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Andorra',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Angola',
    region: 'Middle Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Anguilla',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Antarctica',
    region: 'Antarctica',
    subRegion: '',
    continent: 'Antarctica',
  },
  {
    country: 'Antigua and Barbuda',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Argentina',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'Armenia',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Aruba',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Australia',
    region: 'Australia and New Zealand',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Austria',
    region: 'Western Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Azerbaijan',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Bahamas',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Bahrain',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Bangladesh',
    region: 'Southern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Barbados',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Belarus',
    region: 'Eastern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Belgium',
    region: 'Western Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Belize',
    region: 'Central America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Benin',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Bermuda',
    region: 'Northern America',
    subRegion: '',
    continent: 'North America',
  },
  {
    country: 'Bhutan',
    region: 'Southern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Bolivia',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'Bosnia and Herzegovina',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Botswana',
    region: 'Southern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Bouvet Island',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'Brazil',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'British Indian Ocean Territory',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'British Virgin Islands',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Brunei',
    region: 'South-eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Bulgaria',
    region: 'Eastern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Burkina Faso',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Burundi',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Cape Verde',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Cambodia',
    region: 'South-eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Cameroon',
    region: 'Middle Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Canada',
    region: 'Northern America',
    subRegion: '',
    continent: 'North America',
  },
  {
    country: 'Cayman Islands',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Central African Republic',
    region: 'Middle Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Chad',
    region: 'Middle Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Chile',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'China',
    region: 'Eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Hong Kong',
    region: 'Eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Macao',
    region: 'Eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Christmas Island',
    region: 'Australia and New Zealand',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Cocos Islands',
    region: 'Australia and New Zealand',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Colombia',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'Comoros',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Congo - Kinshasa',
    region: 'Middle Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Congo - Brazzaville',
    region: 'Middle Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Cook Islands',
    region: 'Polynesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Costa Rica',
    region: 'Central America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Ivory Coast',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Croatia',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Cuba',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Netherlands Antilles',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Cyprus',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Czech Republic',
    region: 'Eastern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'North Korea',
    region: 'Eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Denmark',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Djibouti',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Dominica',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Dominican Republic',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Ecuador',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'Egypt',
    region: 'Northern Africa',
    subRegion: '',
    continent: 'Africa',
  },
  {
    country: 'El Salvador',
    region: 'Central America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Equatorial Guinea',
    region: 'Middle Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Eritrea',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Estonia',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Swaziland',
    region: 'Southern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Ethiopia',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Falkland Islands',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'Faroe Islands',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Fiji',
    region: 'Melanesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Finland',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'France',
    region: 'Western Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'French Guiana',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'French Polynesia',
    region: 'Polynesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'French Southern Territories',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Gabon',
    region: 'Middle Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Gambia',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Georgia',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Germany',
    region: 'Western Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Ghana',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Gibraltar',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Greece',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Greenland',
    region: 'Northern America',
    subRegion: '',
    continent: 'North America',
  },
  {
    country: 'Grenada',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Guadeloupe',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Guam',
    region: 'Micronesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Guatemala',
    region: 'Central America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Guernsey',
    region: 'Northern Europe',
    subRegion: 'Channel Islands',
    continent: 'Europe',
  },
  {
    country: 'Guinea',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Guinea-Bissau',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Guyana',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'Haiti',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Heard Island and McDonald Islands',
    region: 'Australia and New Zealand',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Vatican',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Honduras',
    region: 'Central America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Hungary',
    region: 'Eastern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Iceland',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'India',
    region: 'Southern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Indonesia',
    region: 'South-eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Iran',
    region: 'Southern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Iraq',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Ireland',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Isle of Man',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Israel',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Italy',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Jamaica',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Japan',
    region: 'Eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Jersey',
    region: 'Northern Europe',
    subRegion: 'Channel Islands',
    continent: 'Europe',
  },
  {
    country: 'Jordan',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Kazakhstan',
    region: 'Central Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Kenya',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Kiribati',
    region: 'Micronesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Kuwait',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Kyrgyzstan',
    region: 'Central Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Laos',
    region: 'South-eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Latvia',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Lebanon',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Lesotho',
    region: 'Southern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Liberia',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Libya',
    region: 'Northern Africa',
    subRegion: '',
    continent: 'Africa',
  },
  {
    country: 'Liechtenstein',
    region: 'Western Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Lithuania',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Luxembourg',
    region: 'Western Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Madagascar',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Malawi',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Malaysia',
    region: 'South-eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Maldives',
    region: 'Southern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Mali',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Malta',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Marshall Islands',
    region: 'Micronesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Martinique',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Mauritania',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Mauritius',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Mayotte',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Mexico',
    region: 'Central America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Micronesia',
    region: 'Micronesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Monaco',
    region: 'Western Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Mongolia',
    region: 'Eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Montenegro',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Montserrat',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Morocco',
    region: 'Northern Africa',
    subRegion: '',
    continent: 'Africa',
  },
  {
    country: 'Mozambique',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Myanmar',
    region: 'South-eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Namibia',
    region: 'Southern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Nauru',
    region: 'Micronesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Nepal',
    region: 'Southern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Netherlands',
    region: 'Western Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'New Caledonia',
    region: 'Melanesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'New Zealand',
    region: 'Australia and New Zealand',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Nicaragua',
    region: 'Central America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Niger',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Nigeria',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Niue',
    region: 'Polynesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Norfolk Island',
    region: 'Australia and New Zealand',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Macedonia',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Northern Mariana Islands',
    region: 'Micronesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Norway',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Oman',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Pakistan',
    region: 'Southern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Palau',
    region: 'Micronesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Panama',
    region: 'Central America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Papua New Guinea',
    region: 'Melanesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Paraguay',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'Peru',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'Philippines',
    region: 'South-eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Pitcairn',
    region: 'Polynesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Poland',
    region: 'Eastern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Portugal',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Puerto Rico',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Qatar',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'South Korea',
    region: 'Eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Moldova',
    region: 'Eastern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Reunion',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Romania',
    region: 'Eastern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Russia',
    region: 'Eastern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Rwanda',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Saint Helena',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Saint Kitts and Nevis',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Saint Lucia',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Saint Martin (French Part)',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Saint Pierre and Miquelon',
    region: 'Northern America',
    subRegion: '',
    continent: 'North America',
  },
  {
    country: 'Saint Vincent and the Grenadines',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Samoa',
    region: 'Polynesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'San Marino',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Sao Tome and Principe',
    region: 'Middle Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Saudi Arabia',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Senegal',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Serbia',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Seychelles',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Sierra Leone',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Singapore',
    region: 'South-eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Sint Maarten (Dutch part)',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Slovakia',
    region: 'Eastern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Slovenia',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Solomon Islands',
    region: 'Melanesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Somalia',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'South Africa',
    region: 'Southern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'South Georgia and the South Sandwich Islands',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'South Sudan',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Spain',
    region: 'Southern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Sri Lanka',
    region: 'Southern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Palestinian Territory',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Sudan',
    region: 'Northern Africa',
    subRegion: '',
    continent: 'Africa',
  },
  {
    country: 'Suriname',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'Svalbard And Jan Mayen',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Sweden',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Switzerland',
    region: 'Western Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Syria',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Tajikistan',
    region: 'Central Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Thailand',
    region: 'South-eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'East Timor',
    region: 'South-eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Togo',
    region: 'Western Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Tokelau',
    region: 'Polynesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Tonga',
    region: 'Polynesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Trinidad and Tobago',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Tunisia',
    region: 'Northern Africa',
    subRegion: '',
    continent: 'Africa',
  },
  {
    country: 'Turkey',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Turkmenistan',
    region: 'Central Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Turks and Caicos Islands',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Tuvalu',
    region: 'Polynesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Uganda',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Ukraine',
    region: 'Eastern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'United Arab Emirates',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'United Kingdom',
    region: 'Northern Europe',
    subRegion: '',
    continent: 'Europe',
  },
  {
    country: 'Tanzania',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'United States Minor Outlying Islands',
    region: 'Micronesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'United States',
    region: 'Northern America',
    subRegion: '',
    continent: 'North America',
  },
  {
    country: 'U.S. Virgin Islands',
    region: 'Caribbean',
    subRegion: 'Latin America and the Caribbean',
    continent: 'North America',
  },
  {
    country: 'Uruguay',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'Uzbekistan',
    region: 'Central Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Vanuatu',
    region: 'Melanesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Venezuela',
    region: 'South America',
    subRegion: 'Latin America and the Caribbean',
    continent: 'South America',
  },
  {
    country: 'Vietnam',
    region: 'South-eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Wallis and Futuna',
    region: 'Polynesia',
    subRegion: '',
    continent: 'Oceania',
  },
  {
    country: 'Western Sahara',
    region: 'Northern Africa',
    subRegion: '',
    continent: 'Africa',
  },
  {
    country: 'Yemen',
    region: 'Western Asia',
    subRegion: '',
    continent: 'Asia',
  },
  {
    country: 'Zambia',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Zimbabwe',
    region: 'Eastern Africa',
    subRegion: 'Sub-Saharan Africa',
    continent: 'Africa',
  },
  {
    country: 'Taiwan',
    region: 'Eastern Asia',
    subRegion: '',
    continent: 'Asia',
  },
];
