module.exports = [
  [{v: 'US-AK', f: 'Alaska'}, 0, ''],
  [{v: 'US-AL', f: 'Alabama'}, 0, ''],
  [{v: 'US-AZ', f: 'Arizona'}, 0, ''],
  [{v: 'US-AR', f: 'Arkansas'}, 0, ''],
  [{v: 'US-CA', f: 'California'}, 0, ''],
  [{v: 'US-CO', f: 'Colorado'}, 0, ''],
  [{v: 'US-CT', f: 'Connecticut'}, 0, ''],
  [{v: 'US-DE', f: 'Delaware'}, 0, ''],
  [{v: 'US-FL', f: 'Florida'}, 0, ''],
  [{v: 'US-GA', f: 'Georgia'}, 0, ''],
  [{v: 'US-HI', f: 'Hawaii'}, 0, ''],
  [{v: 'US-ID', f: 'Idaho'}, 0, ''],
  [{v: 'US-IL', f: 'Illinois'}, 0, ''],
  [{v: 'US-IN', f: 'Indiana'}, 0, ''],
  [{v: 'US-IA', f: 'Iowa'}, 0, ''],
  [{v: 'US-KS', f: 'Kansas'}, 0, ''],
  [{v: 'US-KY', f: 'Kentucky'}, 0, ''],
  [{v: 'US-LA', f: 'Louisiana'}, 0, ''],
  [{v: 'US-ME', f: 'Maine'}, 0, ''],
  [{v: 'US-MD', f: 'Maryland'}, 0, ''],
  [{v: 'US-MA', f: 'Massachusetts'}, 0, ''],
  [{v: 'US-MI', f: 'Michigan'}, 0, ''],
  [{v: 'US-MN', f: 'Minnesota'}, 0, ''],
  [{v: 'US-MS', f: 'Mississippi'}, 0, ''],
  [{v: 'US-MO', f: 'Missouri'}, 0, ''],
  [{v: 'US-MT', f: 'Montana'}, 0, ''],
  [{v: 'US-NE', f: 'Nebraska'}, 0, ''],
  [{v: 'US-NV', f: 'Nevada'}, 0, ''],
  [{v: 'US-NH', f: 'New Hampshire'}, 0, ''],
  [{v: 'US-NJ', f: 'New Jersey'}, 0, ''],
  [{v: 'US-NM', f: 'New Mexico'}, 0, ''],
  [{v: 'US-NY', f: 'New York'}, 0, ''],
  [{v: 'US-NC', f: 'North Carolina'}, 0, ''],
  [{v: 'US-ND', f: 'North Dakota'}, 0, ''],
  [{v: 'US-OH', f: 'Ohio'}, 0, ''],
  [{v: 'US-OK', f: 'Oklahoma'}, 0, ''],
  [{v: 'US-OR', f: 'Oregon'}, 0, ''],
  [{v: 'US-PA', f: 'Pennsylvania'}, 0, ''],
  [{v: 'US-RI', f: 'Rhode Island'}, 0, ''],
  [{v: 'US-SC', f: 'South Carolina'}, 0, ''],
  [{v: 'US-SD', f: 'South Dakota'}, 0, ''],
  [{v: 'US-TN', f: 'Tennessee'}, 0, ''],
  [{v: 'US-TX', f: 'Texas'}, 0, ''],
  [{v: 'US-UT', f: 'Utah'}, 0, ''],
  [{v: 'US-VT', f: 'Vermont'}, 0, ''],
  [{v: 'US-VA', f: 'Virginia'}, 0, ''],
  [{v: 'US-WA', f: 'Washington'}, 0, ''],
  [{v: 'US-WV', f: 'West Virginia'}, 0, ''],
  [{v: 'US-WI', f: 'Wisconsin'}, 0, ''],
  [{v: 'US-WY', f: 'Wyoming'}, 0, '']
];
